### ISSUE TITLE
getting error on installation of espresso++ software

### ISSUE THREAD

**Issue by NABIAHAMAD** [Updownquark/ObServe#11]
Hello,
I am installing espresso++ software on a cluster locally, I do not have root password,  then i got the error in make step after complete 76% which is given bellow-

/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected type-specifier before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected ‘>’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected ‘(’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: ‘fftw_complex’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected primary-expression before ‘>’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:510: error: expected ‘)’ before ‘;’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:512: error: ‘plan’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:512: error: ‘fftw_execute’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp: In member function ‘bool espressopp::interaction::CoulombKSpaceP3M::_computeForce(espressopp::CellList)’:
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: ‘in_array’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected type-specifier before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected ‘>’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected ‘(’ before ‘fftw_complex’
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: ‘fftw_complex’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected primary-expression before ‘>’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:534: error: expected ‘)’ before ‘;’ token
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:536: error: ‘plan’ was not declared in this scope
/UHOME/nabia.dcy2014/espresso/espressopp-1.9.4.1/src/interaction/CoulombKSpaceP3M.hpp:536: error: ‘fftw_execute’ was not declared in this scope
make[2]: *** [src/CMakeFiles/_espressopp.dir/interaction/CoulombKSpaceP3M.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/_espressopp.dir/all] Error 2
make: *** [all] Error 2

What i have to do, Can anyone please help?
Thanks

**Comment by Updownquark** [comment]
I think you may have me confused with someone else.  I do manage the
ObServe repo, a java observables library.  And I also have a repo called E
*x*presso, with an "x", a java-based non-tokenizing parser that doesn't
work yet.  I don't know anything about espresso++ and I haven't written in
c++ for years.

Good luck finding what you need.

Updownquark
